#!/bin/bash

# Verificar si se proporcionó un argumento
if [ -z "$1" ]; then
  echo "Por favor, proporciona un nombre de directorio."
  exit 1
fi

# Asignar el argumento a una variable
PROJECT_DIR=$1

# Verificar si el directorio existe
if [ ! -d "$PROJECT_DIR" ]; then
  echo "El directorio '$PROJECT_DIR' no existe."
  exit 1
fi

# Cambiar al directorio especificado
cd "$PROJECT_DIR" || exit

# Obtener el nombre del directorio para usarlo como nombre de la sesión de tmux
SESSION_NAME=$(basename "$PROJECT_DIR")

# Iniciar una nueva sesión de tmux llamada como el directorio si no existe, o adjuntarse si ya existe
tmux new-session -d -s "$SESSION_NAME"

# Enviar el comando para abrir neovim en el mismo directorio
tmux send-keys -t "$SESSION_NAME" 'nvim .' C-m

# Adjuntarse a la sesión de tmux
tmux attach-session -t "$SESSION_NAME"
